<a href="https://colab.research.google.com/github/logonzalezsa/PPAE/blob/main/02_Cuadernos/PPAE_03_Operaciones_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PROGRAMACIÓN PARA ANÁLISIS DE ESTRUCTURAS

**Universidad Nacional de Colombia – Sede Palmira**  
**Programa Curricular de Ingeniería Agrícola**

### Tema
**Tópicos sobre Programación de Computadores**

### Taller
**Operaciones con Matrices & Aplicaciones en Ingeniería Estructural**

### Ejercicio
**Operaciones fundamentales con una matriz cuadrada**

**Elaborado por:**  
Luis Octavio González Salcedo  
Profesor Titular

## 1. Contexto y objetivo del cuaderno

Las matrices constituyen una herramienta fundamental para la representación y solución de numerosos problemas de ingeniería. En el análisis estructural permiten organizar información, representar sistemas de ecuaciones y formular relaciones entre fuerzas, desplazamientos y propiedades de los elementos estructurales.

Una **matriz cuadrada** es aquella que posee el mismo número de filas y columnas. Su orden puede representarse como:

$$
[A]_{n\times n}
$$

donde $n$ corresponde al número de filas y de columnas de la matriz.

En este cuaderno se construirá una matriz cuadrada de orden $n$, cuyos valores serán generados aleatoriamente y presentarán signos positivos y negativos alternados. El valor de $n$ será definido por el usuario.

A partir de la matriz generada se estudiarán las siguientes propiedades y operaciones:

- matriz traspuesta;
- diagonal principal;
- diagonal superior;
- diagonal inferior;
- traza;
- determinante;
- rango;
- matriz inversa, cuando exista;
- verificación de la matriz inversa.

### Objetivo del cuaderno

Implementar un procedimiento computacional para generar y analizar una matriz cuadrada de orden $n$, aplicando operaciones fundamentales del álgebra matricial y relacionando su formulación matemática con su implementación mediante programación.

In [1]:
# ============================================================
# DEFINICIÓN DEL ORDEN DE LA MATRIZ
# ============================================================

n = int(input("Ingrese el orden n de la matriz cuadrada: "))

print(f"\nSe trabajará con una matriz de orden {n} x {n}.")

Ingrese el orden n de la matriz cuadrada: 5

Se trabajará con una matriz de orden 5 x 5.


## 2. Construcción de la matriz cuadrada

A partir del orden $n$ definido por el usuario se construirá una matriz cuadrada:

$$
[A]_{n\times n}
$$

Los valores de la matriz serán números enteros generados aleatoriamente. De esta manera, cada nueva ejecución del procedimiento puede producir una matriz diferente.

Para incorporar una alternancia entre valores positivos y negativos, se utilizará la posición de cada elemento dentro de la matriz. Si $i$ representa la fila y $j$ la columna, el signo puede establecerse mediante la expresión:

$$
(-1)^{i+j}
$$

De esta manera se obtiene un patrón alternado de signos:

$$
\begin{bmatrix}
+ & - & + & - & \cdots\\
- & + & - & + & \cdots\\
+ & - & + & - & \cdots\\
- & + & - & + & \cdots\\
\vdots & \vdots & \vdots & \vdots & \ddots
\end{bmatrix}
$$

Inicialmente se generarán valores enteros positivos y posteriormente se aplicará este patrón de signos para construir la matriz $A$.

In [2]:
# ============================================================
# CONSTRUCCIÓN DE LA MATRIZ CUADRADA
# ============================================================

import numpy as np

# Inicializar una matriz n x n con ceros
A = np.zeros((n, n), dtype=int)

# Construcción de la matriz
for i in range(n):
    for j in range(n):

        # Generar un número entero aleatorio entre 1 y 20
        valor = np.random.randint(1, 21)

        # Determinar el signo según la posición
        signo = (-1)**(i + j)

        # Asignar el valor a la matriz
        A[i, j] = signo * valor

# Mostrar la matriz obtenida
print("MATRIZ A")
print("--------")
print(A)

MATRIZ A
--------
[[ 18  -2  16 -17  15]
 [-17  16 -12  14 -13]
 [  4  -2  19 -18  10]
 [-15  15  -9  13  -2]
 [ 15 -18   6 -16   1]]


## 3. Matriz traspuesta

La **matriz traspuesta** de una matriz $A$ se obtiene intercambiando sus filas por sus columnas.

Si:

$$
A=[a_{ij}]
$$

su matriz traspuesta se representa como:

$$
A^T=[a_{ji}]
$$

Por tanto, el elemento que ocupa la posición $(i,j)$ en la matriz original ocupará la posición $(j,i)$ en la matriz traspuesta.

Por ejemplo:

$$
A=
\begin{bmatrix}
a_{11} & a_{12} & a_{13}\\
a_{21} & a_{22} & a_{23}\\
a_{31} & a_{32} & a_{33}
\end{bmatrix}
$$

entonces:

$$
A^T=
\begin{bmatrix}
a_{11} & a_{21} & a_{31}\\
a_{12} & a_{22} & a_{32}\\
a_{13} & a_{23} & a_{33}
\end{bmatrix}
$$

En una matriz cuadrada de orden $n$, tanto $A$ como $A^T$ tienen dimensiones $n\times n$.

In [3]:
# ============================================================
# MATRIZ TRASPUESTA
# ============================================================

A_T = A.T

print("MATRIZ ORIGINAL A")
print("-----------------")
print(A)

print("\nMATRIZ TRASPUESTA A^T")
print("---------------------")
print(A_T)

MATRIZ ORIGINAL A
-----------------
[[ 18  -2  16 -17  15]
 [-17  16 -12  14 -13]
 [  4  -2  19 -18  10]
 [-15  15  -9  13  -2]
 [ 15 -18   6 -16   1]]

MATRIZ TRASPUESTA A^T
---------------------
[[ 18 -17   4 -15  15]
 [ -2  16  -2  15 -18]
 [ 16 -12  19  -9   6]
 [-17  14 -18  13 -16]
 [ 15 -13  10  -2   1]]


## 4. Diagonales de una matriz cuadrada

En una matriz cuadrada pueden identificarse diferentes diagonales a partir de la posición de sus elementos.

### Diagonal principal

La **diagonal principal** está formada por los elementos cuyos índices de fila y columna coinciden:

$$
i=j
$$

Para una matriz de orden $n$:

$$
\operatorname{diag}(A)=
[a_{11},a_{22},a_{33},\ldots,a_{nn}]
$$

### Diagonal superior

La **diagonal inmediatamente superior** a la diagonal principal está formada por los elementos para los cuales:

$$
j=i+1
$$

y contiene $n-1$ elementos.

### Diagonal inferior

La **diagonal inmediatamente inferior** a la diagonal principal está formada por los elementos para los cuales:

$$
i=j+1
$$

y también contiene $n-1$ elementos.

Estas diagonales adquieren especial importancia en matrices que presentan una estructura particular, como ocurre en diferentes formulaciones del análisis estructural.

In [4]:
# ============================================================
# DIAGONALES DE LA MATRIZ
# ============================================================

diagonal_principal = np.diag(A)
diagonal_superior = np.diag(A, k=1)
diagonal_inferior = np.diag(A, k=-1)

print("MATRIZ A")
print("--------")
print(A)

print("\nDIAGONAL PRINCIPAL")
print("------------------")
print(diagonal_principal)

print("\nDIAGONAL SUPERIOR")
print("-----------------")
print(diagonal_superior)

print("\nDIAGONAL INFERIOR")
print("-----------------")
print(diagonal_inferior)

MATRIZ A
--------
[[ 18  -2  16 -17  15]
 [-17  16 -12  14 -13]
 [  4  -2  19 -18  10]
 [-15  15  -9  13  -2]
 [ 15 -18   6 -16   1]]

DIAGONAL PRINCIPAL
------------------
[18 16 19 13  1]

DIAGONAL SUPERIOR
-----------------
[ -2 -12 -18  -2]

DIAGONAL INFERIOR
-----------------
[-17  -2  -9 -16]


## 5. Traza de una matriz

La **traza** de una matriz cuadrada $A$ corresponde a la suma de los elementos ubicados en su diagonal principal.

Para una matriz cuadrada de orden $n$:

$$
\operatorname{tr}(A)=
a_{11}+a_{22}+a_{33}+\cdots+a_{nn}
$$

o, de manera compacta:

$$
\operatorname{tr}(A)=\sum_{i=1}^{n}a_{ii}
$$

Por tanto, la traza relaciona directamente una propiedad de la matriz con los elementos de la diagonal principal previamente identificada.

La traza solamente se define para matrices cuadradas y produce como resultado un valor escalar.

In [5]:
# ============================================================
# TRAZA DE LA MATRIZ
# ============================================================

traza = np.trace(A)

print("DIAGONAL PRINCIPAL")
print("------------------")
print(diagonal_principal)

print("\nSUMA DE LOS ELEMENTOS DE LA DIAGONAL PRINCIPAL")
print("-----------------------------------------------")
print(np.sum(diagonal_principal))

print("\nTRAZA DE LA MATRIZ A")
print("--------------------")
print(traza)

DIAGONAL PRINCIPAL
------------------
[18 16 19 13  1]

SUMA DE LOS ELEMENTOS DE LA DIAGONAL PRINCIPAL
-----------------------------------------------
67

TRAZA DE LA MATRIZ A
--------------------
67


## 6. Matrices triangulares

A partir de una matriz cuadrada pueden obtenerse matrices que conservan únicamente los elementos ubicados sobre uno de los lados de su diagonal principal.

### Matriz triangular superior

Una matriz es **triangular superior** cuando todos los elementos ubicados por debajo de la diagonal principal son iguales a cero:

$$
U=
\begin{bmatrix}
u_{11} & u_{12} & u_{13} & \cdots & u_{1n}\\
0 & u_{22} & u_{23} & \cdots & u_{2n}\\
0 & 0 & u_{33} & \cdots & u_{3n}\\
\vdots & \vdots & \vdots & \ddots & \vdots\\
0 & 0 & 0 & \cdots & u_{nn}
\end{bmatrix}
$$

### Matriz triangular inferior

Una matriz es **triangular inferior** cuando todos los elementos ubicados por encima de la diagonal principal son iguales a cero:

$$
L=
\begin{bmatrix}
l_{11} & 0 & 0 & \cdots & 0\\
l_{21} & l_{22} & 0 & \cdots & 0\\
l_{31} & l_{32} & l_{33} & \cdots & 0\\
\vdots & \vdots & \vdots & \ddots & \vdots\\
l_{n1} & l_{n2} & l_{n3} & \cdots & l_{nn}
\end{bmatrix}
$$

### ¿Para qué se utilizan?

Las matrices triangulares son especialmente útiles en la solución de sistemas de ecuaciones lineales.

Un sistema cuya matriz de coeficientes es triangular superior puede resolverse mediante **sustitución hacia atrás**, mientras que un sistema con matriz triangular inferior puede resolverse mediante **sustitución hacia adelante**.

También aparecen como resultado de procedimientos como la **eliminación de Gauss** y en diferentes métodos de **factorización de matrices**.

Estas herramientas son de interés en ingeniería estructural, donde numerosos procedimientos conducen a sistemas de ecuaciones lineales.

In [6]:
# ============================================================
# MATRICES TRIANGULARES
# ============================================================

triangular_superior = np.triu(A)
triangular_inferior = np.tril(A)

print("MATRIZ ORIGINAL A")
print("-----------------")
print(A)

print("\nMATRIZ TRIANGULAR SUPERIOR")
print("--------------------------")
print(triangular_superior)

print("\nMATRIZ TRIANGULAR INFERIOR")
print("--------------------------")
print(triangular_inferior)

MATRIZ ORIGINAL A
-----------------
[[ 18  -2  16 -17  15]
 [-17  16 -12  14 -13]
 [  4  -2  19 -18  10]
 [-15  15  -9  13  -2]
 [ 15 -18   6 -16   1]]

MATRIZ TRIANGULAR SUPERIOR
--------------------------
[[ 18  -2  16 -17  15]
 [  0  16 -12  14 -13]
 [  0   0  19 -18  10]
 [  0   0   0  13  -2]
 [  0   0   0   0   1]]

MATRIZ TRIANGULAR INFERIOR
--------------------------
[[ 18   0   0   0   0]
 [-17  16   0   0   0]
 [  4  -2  19   0   0]
 [-15  15  -9  13   0]
 [ 15 -18   6 -16   1]]


## 7. Determinante de una matriz

El **determinante** es un valor escalar asociado a una matriz cuadrada y se representa como:

$$
\det(A)
$$

o también:

$$
|A|
$$

El determinante proporciona información importante sobre las propiedades de una matriz.

En particular:

- Si $\det(A)\neq 0$, la matriz es **no singular** y posee matriz inversa.
- Si $\det(A)=0$, la matriz es **singular** y no posee matriz inversa.

Esta propiedad resulta especialmente importante cuando una matriz representa los coeficientes de un sistema de ecuaciones lineales.

Para un sistema:

$$
[A]\{x\}=\{b\}
$$

un determinante diferente de cero indica que la matriz $A$ es invertible y que el sistema posee una solución única.

En problemas de ingeniería estructural, esta condición adquiere especial importancia cuando se formulan sistemas matriciales para determinar incógnitas como fuerzas, reacciones o desplazamientos.

In [7]:
# ============================================================
# DETERMINANTE DE LA MATRIZ
# ============================================================

determinante = np.linalg.det(A)

print("MATRIZ ORIGINAL A")
print("-----------------")
print(A)

print("\nDETERMINANTE DE A")
print("----------------")
print(determinante)

MATRIZ ORIGINAL A
-----------------
[[ 18  -2  16 -17  15]
 [-17  16 -12  14 -13]
 [  4  -2  19 -18  10]
 [-15  15  -9  13  -2]
 [ 15 -18   6 -16   1]]

DETERMINANTE DE A
----------------
198855.99999999994


### Observación sobre la precisión numérica

El determinante calculado mediante `NumPy` puede presentar pequeñas diferencias respecto al valor matemático esperado debido al uso de **aritmética de punto flotante**.

Por esta razón, cuando el resultado se encuentra muy próximo a un número entero, puede utilizarse una aproximación mediante redondeo para facilitar su interpretación.

Esta diferencia no representa necesariamente un error en el procedimiento, sino que puede ser consecuencia de la representación numérica utilizada por el computador.

Además:

- Si $\det(A)\neq 0$, la matriz es **no singular**.
- Si $\det(A)=0$, la matriz es **singular**.

Esta condición permitirá posteriormente analizar la existencia de la matriz inversa.

In [8]:
# ============================================================
# DETERMINANTE DE LA MATRIZ
# ============================================================

determinante = np.linalg.det(A)

print("MATRIZ ORIGINAL A")
print("-----------------")
print(A)

print("\nDETERMINANTE CALCULADO")
print("----------------------")
print(determinante)

print("\nDETERMINANTE APROXIMADO")
print("-----------------------")
print(round(determinante))

MATRIZ ORIGINAL A
-----------------
[[ 18  -2  16 -17  15]
 [-17  16 -12  14 -13]
 [  4  -2  19 -18  10]
 [-15  15  -9  13  -2]
 [ 15 -18   6 -16   1]]

DETERMINANTE CALCULADO
----------------------
198855.99999999994

DETERMINANTE APROXIMADO
-----------------------
198856


## 8. Rango de una matriz

El **rango** de una matriz corresponde al número máximo de filas o columnas linealmente independientes que contiene.

Para una matriz cuadrada de orden $n$:

$$
[A]_{n\times n}
$$

el rango puede tomar valores entre $0$ y $n$:

$$
0\leq \operatorname{rango}(A)\leq n
$$

Cuando:

$$
\operatorname{rango}(A)=n
$$

se dice que la matriz posee **rango completo**.

Para una matriz cuadrada, existe una relación importante entre el rango y el determinante:

$$
\det(A)\neq0
\quad\Longleftrightarrow\quad
\operatorname{rango}(A)=n
$$

En este caso, la matriz es no singular y posee matriz inversa.

Por el contrario, si:

$$
\operatorname{rango}(A)<n
$$

la matriz no tiene rango completo, es singular y su determinante es cero.

El análisis del rango permite identificar la independencia de las ecuaciones que conforman un sistema lineal, aspecto importante en la formulación y solución de problemas de ingeniería.

In [9]:
# ============================================================
# RANGO DE LA MATRIZ
# ============================================================

rango = np.linalg.matrix_rank(A)

print("MATRIZ ORIGINAL A")
print("-----------------")
print(A)

print("\nORDEN DE LA MATRIZ")
print("------------------")
print(n)

print("\nRANGO DE LA MATRIZ A")
print("--------------------")
print(rango)

if rango == n:
    print("\nLa matriz tiene rango completo.")
else:
    print("\nLa matriz NO tiene rango completo.")

MATRIZ ORIGINAL A
-----------------
[[ 18  -2  16 -17  15]
 [-17  16 -12  14 -13]
 [  4  -2  19 -18  10]
 [-15  15  -9  13  -2]
 [ 15 -18   6 -16   1]]

ORDEN DE LA MATRIZ
------------------
5

RANGO DE LA MATRIZ A
--------------------
5

La matriz tiene rango completo.


## 9. Matriz inversa

La **matriz inversa** de una matriz cuadrada $A$ se representa como:

$$
A^{-1}
$$

y se define como aquella matriz que, al multiplicarse por la matriz original, produce la matriz identidad:

$$
AA^{-1}=A^{-1}A=I
$$

donde $I$ es la **matriz identidad** de orden $n$:

$$
I=
\begin{bmatrix}
1 & 0 & 0 & \cdots & 0\\
0 & 1 & 0 & \cdots & 0\\
0 & 0 & 1 & \cdots & 0\\
\vdots & \vdots & \vdots & \ddots & \vdots\\
0 & 0 & 0 & \cdots & 1
\end{bmatrix}
$$

Una matriz cuadrada posee inversa únicamente cuando es **no singular**.

Las condiciones estudiadas anteriormente permiten establecer que:

$$
\det(A)\neq0
\quad\Longleftrightarrow\quad
\operatorname{rango}(A)=n
\quad\Longleftrightarrow\quad
A^{-1}\text{ existe}
$$

Por tanto, antes de calcular la matriz inversa es conveniente verificar que la matriz cumple estas condiciones.

La matriz inversa tiene especial importancia en la solución de sistemas de ecuaciones lineales. Si:

$$
[A]\{x\}=\{b\}
$$

y $A^{-1}$ existe, entonces:

$$
\{x\}=A^{-1}\{b\}
$$

Esta relación será utilizada posteriormente en la solución matricial de problemas de análisis estructural.

In [10]:
# ============================================================
# MATRIZ INVERSA
# ============================================================

print("MATRIZ ORIGINAL A")
print("-----------------")
print(A)

if rango == n:

    A_inversa = np.linalg.inv(A)

    print("\nMATRIZ INVERSA A^-1")
    print("--------------------")

    # Mostrar los resultados con cuatro cifras decimales
    print(np.round(A_inversa, 4))

else:

    print("\nLa matriz no tiene rango completo.")
    print("Por tanto, la matriz inversa no existe.")

MATRIZ ORIGINAL A
-----------------
[[ 18  -2  16 -17  15]
 [-17  16 -12  14 -13]
 [  4  -2  19 -18  10]
 [-15  15  -9  13  -2]
 [ 15 -18   6 -16   1]]

MATRIZ INVERSA A^-1
--------------------
[[ 0.0648  0.0398 -0.0595 -0.0906 -0.0407]
 [ 0.0704  0.0707 -0.0125  0.0115  0.0105]
 [-0.0384  0.0075  0.0405 -0.2239 -0.1802]
 [-0.0328 -0.0455 -0.0267 -0.1723 -0.1774]
 [ 0.0021 -0.0979 -0.0038  0.1538  0.0414]]


### 9.1 Verificación de la matriz inversa

Una forma de comprobar el resultado consiste en multiplicar la matriz original por la matriz inversa calculada:

$$
AA^{-1}=I
$$

El resultado esperado es la **matriz identidad**.

Debido a la aritmética de punto flotante utilizada en los cálculos computacionales, algunos elementos pueden presentar valores numéricos extremadamente pequeños en lugar de cero exacto.

Por esta razón, además de observar el producto obtenido, puede verificarse numéricamente si este es suficientemente cercano a la matriz identidad.

In [11]:
# ============================================================
# VERIFICACIÓN DE LA MATRIZ INVERSA
# ============================================================

if rango == n:

    producto = A @ A_inversa
    identidad = np.eye(n)

    print("MATRIZ ORIGINAL A")
    print("-----------------")
    print(A)

    print("\nMATRIZ INVERSA A^-1")
    print("--------------------")
    print(np.round(A_inversa, 4))

    print("\nPRODUCTO A @ A^-1")
    print("------------------")
    print(np.round(producto, 4))

    print("\nMATRIZ IDENTIDAD I")
    print("------------------")
    print(identidad)

    print("\n¿A @ A^-1 es aproximadamente igual a I?")
    print(np.allclose(producto, identidad))

else:

    print("No es posible realizar la verificación porque la matriz inversa no existe.")

MATRIZ ORIGINAL A
-----------------
[[ 18  -2  16 -17  15]
 [-17  16 -12  14 -13]
 [  4  -2  19 -18  10]
 [-15  15  -9  13  -2]
 [ 15 -18   6 -16   1]]

MATRIZ INVERSA A^-1
--------------------
[[ 0.0648  0.0398 -0.0595 -0.0906 -0.0407]
 [ 0.0704  0.0707 -0.0125  0.0115  0.0105]
 [-0.0384  0.0075  0.0405 -0.2239 -0.1802]
 [-0.0328 -0.0455 -0.0267 -0.1723 -0.1774]
 [ 0.0021 -0.0979 -0.0038  0.1538  0.0414]]

PRODUCTO A @ A^-1
------------------
[[ 1.  0.  0.  0. -0.]
 [-0.  1. -0.  0.  0.]
 [ 0. -0.  1.  0.  0.]
 [-0. -0. -0.  1.  0.]
 [ 0. -0.  0. -0.  1.]]

MATRIZ IDENTIDAD I
------------------
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

¿A @ A^-1 es aproximadamente igual a I?
True


## 10. Aplicación en análisis estructural

Las operaciones matriciales desarrolladas en este cuaderno constituyen herramientas fundamentales para la formulación y solución computacional de problemas de ingeniería.

En el **análisis estructural**, las matrices permiten organizar y relacionar diferentes variables del problema, como fuerzas, reacciones, desplazamientos y propiedades de los elementos estructurales.

Su utilización permite, entre otras aplicaciones:

- representar sistemas de ecuaciones de equilibrio;
- organizar los coeficientes asociados a las incógnitas de un problema;
- resolver sistemas de ecuaciones lineales;
- formular relaciones entre fuerzas y desplazamientos;
- representar matrices de rigidez de elementos y estructuras;
- implementar procedimientos computacionales para el análisis de sistemas estructurales.

De esta manera, las matrices no constituyen únicamente una herramienta matemática, sino una forma eficiente de **representar, organizar y resolver computacionalmente problemas de análisis estructural**.

## Reflexión final

El **álgebra lineal** constituye uno de los lenguajes matemáticos fundamentales de la computación científica. Mediante vectores y matrices es posible representar grandes cantidades de información y expresar de manera compacta relaciones que, escritas individualmente, podrían involucrar numerosos cálculos y ecuaciones.

En ingeniería, esta capacidad permite transformar un problema físico en un **modelo matemático** y posteriormente en un **procedimiento computacional** capaz de ser ejecutado, verificado y aplicado a sistemas de mayor complejidad.

En el análisis estructural, las matrices permiten representar sistemas de equilibrio, relaciones entre fuerzas y desplazamientos, propiedades de los elementos y ecuaciones de rigidez. A medida que aumenta el número de elementos, nodos y grados de libertad de una estructura, el tratamiento matricial deja de ser solamente conveniente y se convierte en una herramienta esencial para su análisis computacional.

Su importancia, sin embargo, trasciende el análisis estructural. El álgebra lineal está presente en campos como:

- simulación numérica;
- optimización;
- análisis de datos;
- procesamiento de imágenes;
- aprendizaje automático;
- redes neuronales e inteligencia artificial;
- métodos de elementos finitos.

Por esta razón, comprender las operaciones matriciales no consiste únicamente en aprender a utilizar instrucciones de una biblioteca computacional. Significa comprender parte del **lenguaje matemático mediante el cual muchos problemas de ingeniería pueden ser representados y resueltos por un computador**.

> **Programar una matriz no reemplaza el razonamiento matemático ni ingenieril: permite llevarlo a una escala que difícilmente podría abordarse mediante cálculos manuales.**