<a href="https://colab.research.google.com/github/logonzalezsa/PPAE/blob/main/02_Cuadernos/PPAE_04_Armaduras_SolucionMatricial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PROGRAMACIÓN PARA ANÁLISIS DE ESTRUCTURAS

**Universidad Nacional de Colombia – Sede Palmira**  
**Programa Curricular de Ingeniería Agrícola**

### Tema
**Solución Matricial de Sistemas de Ecuaciones**

### Taller
**Aplicación del Método de los Nudos en Armaduras**

### Ejercicio
**Determinación de fuerzas en los miembros y reacciones en los apoyos**

**Elaborado por:**  
Luis Octavio González Salcedo  
Profesor Titular

## 1. Contexto y objetivo del cuaderno

El análisis de una armadura mediante el **método de los nudos** se fundamenta en la aplicación de las ecuaciones de equilibrio en cada uno de sus nodos:

$$
\sum F_x=0
$$

$$
\sum F_y=0
$$

La aplicación sistemática de estas condiciones genera un conjunto de ecuaciones lineales cuyas incógnitas corresponden a las **fuerzas internas en los miembros de la armadura** y a las **reacciones en los apoyos**.

Cuando aumenta el número de miembros y nudos, la solución manual del sistema de ecuaciones puede resultar extensa. El álgebra matricial permite organizar estas ecuaciones mediante la expresión:

$$
[K_T]\{T\}=\{P\}
$$

donde:

- $[K_T]$ es la matriz de coeficientes del sistema;
- $\{T\}$ es el vector de incógnitas, que contiene las fuerzas en los miembros y las reacciones;
- $\{P\}$ es el vector de términos independientes asociado a las cargas conocidas.

### Objetivo del cuaderno

Implementar un procedimiento computacional para organizar y resolver el sistema de ecuaciones obtenido mediante el equilibrio de los nudos de una armadura, utilizando su representación matricial para determinar las fuerzas internas de sus miembros y las reacciones en los apoyos.

## 2. Del sistema de ecuaciones a la representación matricial

El procedimiento desarrollado en este cuaderno puede aplicarse a un **sistema lineal de $n$ ecuaciones con $n$ incógnitas**.

Como ejemplo de aplicación se utilizará el sistema de ecuaciones obtenido mediante el **equilibrio de los nudos de una armadura**. Para cada nudo se aplicaron las condiciones de equilibrio:

$$
\sum F_x=0
$$

$$
\sum F_y=0
$$

obteniéndose un conjunto de ecuaciones cuyas incógnitas corresponden a las fuerzas internas en los miembros y a las reacciones en los apoyos.

Para la armadura utilizada como ejemplo se obtuvo el siguiente sistema:

$$
F_1+0.5F_2+A_x=0
$$

$$
0.866F_2+A_y=0
$$

$$
-0.5F_2+0.5F_3+F_4=0
$$

$$
-0.866F_2-0.866F_3=400
$$

$$
-0.5F_3+0.5F_5+F_6=0
$$

$$
0.866F_3+0.866F_5=0
$$

$$
-F_4-0.5F_5+0.5F_7=0
$$

$$
-0.866F_5-0.866F_7=800
$$

$$
-F_6-0.5F_7=0
$$

$$
0.866F_7+E_y=0
$$

Este sistema constituye únicamente el **caso de aplicación utilizado para ilustrar el procedimiento computacional**.

Las celdas de ejecución serán formuladas de manera general, permitiendo ingresar y resolver otros sistemas de $n$ ecuaciones con $n$ incógnitas, siempre que estos hayan sido previamente formulados y organizados de manera adecuada.

Para el ejemplo presentado se tienen **10 ecuaciones y 10 incógnitas**.

### 2.1 De una ecuación a una fila de la matriz

En un sistema lineal, cada ecuación genera una fila de la matriz de coeficientes.

En el caso de la armadura utilizada como ejemplo, estas ecuaciones provienen de la aplicación de las condiciones de equilibrio en sus nudos.

Por ejemplo, para la primera ecuación:

$$
F_1+0.5F_2+A_x=0
$$

y utilizando el orden de incógnitas:

$$
[F_1,\;F_2,\;F_3,\;F_4,\;F_5,\;F_6,\;F_7,\;A_x,\;A_y,\;E_y]
$$

los coeficientes correspondientes son:

$$
[1,\;0.5,\;0,\;0,\;0,\;0,\;0,\;1,\;0,\;0]
$$

Este vector constituye la **primera fila de la matriz de coeficientes $[K_T]$**.

Los valores iguales a cero indican que las respectivas incógnitas no participan en esa ecuación.

El mismo procedimiento puede aplicarse sistemáticamente a cada una de las ecuaciones hasta completar la matriz de coeficientes del sistema.

In [1]:
# ============================================================
# DEFINICIÓN DEL SISTEMA DE ECUACIONES
# ============================================================

import numpy as np

# Número de ecuaciones del sistema
n = int(input("Ingrese el número de ecuaciones del sistema: "))

# Inicializar la matriz de coeficientes y el vector independiente
KT = np.zeros((n, n), dtype=float)
P = np.zeros((n, 1), dtype=float)

print(f"\nSe trabajará con un sistema de {n} ecuaciones y {n} incógnitas.")

print("\nMATRIZ DE COEFICIENTES [KT]")
print("---------------------------")
print(KT)

print("\nVECTOR DE TÉRMINOS INDEPENDIENTES {P}")
print("-------------------------------------")
print(P)

Ingrese el número de ecuaciones del sistema: 10

Se trabajará con un sistema de 10 ecuaciones y 10 incógnitas.

MATRIZ DE COEFICIENTES [KT]
---------------------------
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

VECTOR DE TÉRMINOS INDEPENDIENTES {P}
-------------------------------------
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [2]:
# ============================================================
# INGRESO DE LAS INCÓGNITAS Y ECUACIONES DEL SISTEMA
# ============================================================

# Leer los nombres de las incógnitas
while True:
    nombres = input(
        f"Ingrese los nombres de las {n} incógnitas separados por espacios:\n"
    ).split()

    if len(nombres) == n:
        break
    else:
        print(f"\nDebe ingresar exactamente {n} nombres.")
        print(f"Se ingresaron {len(nombres)}. Intente nuevamente.\n")


print("\nORDEN DE LAS INCÓGNITAS")
print("-----------------------")
print("   ".join(nombres))


# Leer las ecuaciones una por una
for i in range(n):

    print("\n" + "=" * 60)
    print(f"ECUACIÓN {i + 1}")
    print("=" * 60)

    print("\nOrden de las incógnitas:")
    print("   ".join(nombres))

    # Leer y verificar los coeficientes de la ecuación
    while True:

        entrada = input(
            f"\nIngrese los {n} coeficientes separados por espacios:\n"
        )

        try:
            coeficientes = [float(x) for x in entrada.split()]

            if len(coeficientes) == n:
                break
            else:
                print(
                    f"\nDebe ingresar exactamente {n} coeficientes. "
                    f"Se ingresaron {len(coeficientes)}."
                )

        except ValueError:
            print("\nTodos los coeficientes deben ser valores numéricos.")

    # Guardar los coeficientes en la fila correspondiente de KT
    KT[i, :] = coeficientes

    # Leer el término independiente
    while True:
        try:
            P[i, 0] = float(
                input("\nIngrese el término independiente de la ecuación: ")
            )
            break

        except ValueError:
            print("\nEl término independiente debe ser un valor numérico.")

    # Mostrar cómo se va construyendo el sistema
    print("\nMATRIZ [KT] ACTUALIZADA")
    print("-----------------------")
    print(KT)

    print("\nVECTOR {P} ACTUALIZADO")
    print("----------------------")
    print(P)

Ingrese los nombres de las 10 incógnitas separados por espacios:
F1 F2 F3 F4 F5 F6 F7 Ax Ay Ey

ORDEN DE LAS INCÓGNITAS
-----------------------
F1   F2   F3   F4   F5   F6   F7   Ax   Ay   Ey

ECUACIÓN 1

Orden de las incógnitas:
F1   F2   F3   F4   F5   F6   F7   Ax   Ay   Ey

Ingrese los 10 coeficientes separados por espacios:
1 0.5 0 0 0 0 0 1 0 0

Ingrese el término independiente de la ecuación: 0

MATRIZ [KT] ACTUALIZADA
-----------------------
[[1.  0.5 0.  0.  0.  0.  0.  1.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]]

VECTOR {P} ACTUALIZADO
----------------------
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]

ECUACI

## 3. Verificación del sistema matricial

Una vez construidos la matriz de coeficientes $[K_T]$ y el vector de términos independientes $\{P\}$, es conveniente verificar las características del sistema antes de proceder a su solución.

El sistema general puede expresarse como:

$$
[K_T]\{T\}=\{P\}
$$

Para un sistema de $n$ ecuaciones con $n$ incógnitas, la matriz $[K_T]$ debe ser cuadrada:

$$
[K_T]_{n\times n}
$$

Antes de calcular las incógnitas se analizarán:

- las dimensiones de la matriz $[K_T]$ y del vector $\{P\}$;
- el determinante de $[K_T]$;
- el rango de $[K_T]$.

Si:

$$
\det(K_T)\neq0
$$

y:

$$
\operatorname{rango}(K_T)=n
$$

la matriz posee rango completo, es no singular y tiene inversa. En estas condiciones, el sistema lineal posee una solución única.

Esta verificación permite comprobar matemáticamente que el sistema ingresado puede ser resuelto antes de realizar el cálculo de las incógnitas.

In [3]:
# ============================================================
# VERIFICACIÓN DEL SISTEMA MATRICIAL
# ============================================================

print("SISTEMA MATRICIAL INGRESADO")
print("===========================")

print("\nORDEN DE LAS INCÓGNITAS")
print("-----------------------")
print("   ".join(nombres))

print("\nMATRIZ DE COEFICIENTES [KT]")
print("---------------------------")
print(KT)

print("\nVECTOR DE TÉRMINOS INDEPENDIENTES {P}")
print("-------------------------------------")
print(P)

# Dimensiones
print("\nDIMENSIONES DEL SISTEMA")
print("-----------------------")
print(f"[KT] : {KT.shape}")
print(f"{{P}}  : {P.shape}")

# Determinante y rango
det_KT = np.linalg.det(KT)
rango_KT = np.linalg.matrix_rank(KT)

print("\nDETERMINANTE DE [KT]")
print("--------------------")
print(det_KT)

print("\nRANGO DE [KT]")
print("-------------")
print(rango_KT)

# Interpretación
print("\nVERIFICACIÓN")
print("------------")

if np.isclose(det_KT, 0):

    print("La matriz [KT] es singular.")
    print("El sistema no presenta una solución única.")

elif rango_KT == n:

    print("La matriz [KT] tiene rango completo.")
    print("La matriz [KT] es no singular.")
    print("El sistema presenta una solución única.")

else:

    print("La matriz [KT] no tiene rango completo.")
    print("El sistema no presenta una solución única.")

SISTEMA MATRICIAL INGRESADO

ORDEN DE LAS INCÓGNITAS
-----------------------
F1   F2   F3   F4   F5   F6   F7   Ax   Ay   Ey

MATRIZ DE COEFICIENTES [KT]
---------------------------
[[ 1.     0.5    0.     0.     0.     0.     0.     1.     0.     0.   ]
 [ 0.     0.866  0.     0.     0.     0.     0.     0.     1.     0.   ]
 [ 0.    -0.5    0.5    1.     0.     0.     0.     0.     0.     0.   ]
 [ 0.    -0.866 -0.866  0.     0.     0.     0.     0.     0.     0.   ]
 [-1.     0.    -0.5    0.     0.5    1.     0.     0.     0.     0.   ]
 [ 0.     0.     0.866  0.     0.866  0.     0.     0.     0.     0.   ]
 [ 0.     0.     0.    -1.    -0.5    0.     0.5    0.     0.     0.   ]
 [ 0.     0.     0.     0.    -0.866  0.    -0.866  0.     0.     0.   ]
 [ 0.     0.     0.     0.     0.    -1.    -0.5    0.     0.     0.   ]
 [ 0.     0.     0.     0.     0.     0.     0.866  0.     0.     1.   ]]

VECTOR DE TÉRMINOS INDEPENDIENTES {P}
-------------------------------------
[[  0.]
 [

## 4. Solución del sistema mediante la matriz inversa

Una vez comprobado que la matriz $[K_T]$ es no singular y posee rango completo, puede calcularse su matriz inversa.

Partiendo del sistema:

$$
[K_T]\{T\}=\{P\}
$$

y multiplicando ambos lados por $[K_T]^{-1}$:

$$
[K_T]^{-1}[K_T]\{T\}=[K_T]^{-1}\{P\}
$$

como:

$$
[K_T]^{-1}[K_T]=[I]
$$

se obtiene:

$$
\boxed{\{T\}=[K_T]^{-1}\{P\}}
$$

El vector $\{T\}$ contiene los valores de las incógnitas respetando exactamente el orden establecido durante la construcción del sistema.

En el ejemplo de la armadura:

$$
\{T\}=
\begin{Bmatrix}
F_1 & F_2 & F_3 & F_4 & F_5 & F_6 & F_7 & A_x & A_y & E_y
\end{Bmatrix}^{T}
$$

Por tanto, los primeros valores corresponden a las fuerzas internas de los miembros y los últimos a las reacciones en los apoyos.

In [4]:
# ============================================================
# SOLUCIÓN DEL SISTEMA MEDIANTE LA MATRIZ INVERSA
# ============================================================

if rango_KT == n and not np.isclose(det_KT, 0):

    # Calcular la matriz inversa
    KT_inversa = np.linalg.inv(KT)

    # Calcular el vector de incógnitas
    T = KT_inversa @ P

    print("MATRIZ INVERSA [KT]^-1")
    print("-----------------------")
    print(np.round(KT_inversa, 4))

    print("\nVECTOR SOLUCIÓN {T}")
    print("-------------------")
    print(np.round(T, 4))

    print("\nRESULTADOS")
    print("----------")

    for i in range(n):
        print(f"{nombres[i]} = {T[i, 0]:.4f}")

else:

    print("El sistema no posee una solución única.")
    print("No es posible aplicar este procedimiento.")

MATRIZ INVERSA [KT]^-1
-----------------------
[[ 0.      0.     -0.75    0.433  -1.      0.2887 -0.75    0.1443 -1.
   0.    ]
 [ 0.      0.     -0.5    -0.8661  0.     -0.5774 -0.5    -0.2887  0.
   0.    ]
 [-0.     -0.      0.5    -0.2887 -0.      0.5774  0.5     0.2887 -0.
  -0.    ]
 [ 0.      0.      0.5    -0.2887  0.     -0.5774 -0.5    -0.2887  0.
   0.    ]
 [ 0.      0.     -0.5     0.2887  0.      0.5774 -0.5    -0.2887  0.
   0.    ]
 [ 0.      0.     -0.25    0.1443  0.      0.2887 -0.25    0.433  -1.
   0.    ]
 [-0.     -0.      0.5    -0.2887 -0.     -0.5774  0.5    -0.8661 -0.
  -0.    ]
 [ 1.      0.      1.      0.      1.      0.      1.      0.      1.
   0.    ]
 [ 0.      1.      0.433   0.75    0.      0.5     0.433   0.25    0.
   0.    ]
 [ 0.      0.     -0.433   0.25    0.      0.5    -0.433   0.75    0.
   1.    ]]

VECTOR SOLUCIÓN {T}
-------------------
[[ 288.6836]
 [-577.3672]
 [ 115.4734]
 [-346.4203]
 [-115.4734]
 [ 404.157 ]
 [-808.3141]
 [   0.   

### 4.1 Verificación de la solución

La obtención del vector de incógnitas no constituye por sí sola la finalización del procedimiento computacional. Es conveniente verificar que los valores calculados satisfacen el sistema de ecuaciones original.

Partiendo de:

$$
[K_T]\{T\}=\{P\}
$$

se utiliza el vector solución obtenido para calcular:

$$
\{P_{calculado}\}=[K_T]\{T\}
$$

Si la solución es correcta, debe cumplirse:

$$
\{P_{calculado}\}\approx\{P\}
$$

Debido a la aritmética de punto flotante, pueden presentarse diferencias numéricas extremadamente pequeñas. Por esta razón, la comparación computacional se realiza considerando una tolerancia numérica.

Esta verificación permite comprobar que el vector solución satisface el sistema de ecuaciones ingresado.

In [6]:
# ============================================================
# VERIFICACIÓN DE LA SOLUCIÓN
# ============================================================

P_calculado = KT @ T
diferencia = P_calculado - P

print("VECTOR ORIGINAL {P}")
print("-------------------")
print(P)

print("\nVECTOR RECALCULADO [KT]{T}")
print("--------------------------")
print(np.round(P_calculado, 6))

print("\nDIFERENCIA [KT]{T} - {P}")
print("-------------------------")
print(np.round(diferencia, 10))

print("\n¿LA SOLUCIÓN SATISFACE EL SISTEMA?")
print("----------------------------------")
print(np.allclose(P_calculado, P))

VECTOR ORIGINAL {P}
-------------------
[[  0.]
 [  0.]
 [  0.]
 [400.]
 [  0.]
 [  0.]
 [  0.]
 [800.]
 [  0.]
 [  0.]]

VECTOR RECALCULADO [KT]{T}
--------------------------
[[  0.]
 [  0.]
 [  0.]
 [400.]
 [  0.]
 [  0.]
 [  0.]
 [800.]
 [ -0.]
 [  0.]]

DIFERENCIA [KT]{T} - {P}
-------------------------
[[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [-0.]
 [-0.]
 [ 0.]]

¿LA SOLUCIÓN SATISFACE EL SISTEMA?
----------------------------------
True


## 5. Interpretación estructural de los resultados

La solución del sistema matricial proporciona los valores algebraicos de las fuerzas internas en los miembros y de las reacciones en los apoyos.

Para formular las ecuaciones de equilibrio de los nudos se adoptó inicialmente que las fuerzas internas de los miembros se encontraban a **tracción**, es decir, actuando hacia afuera de cada nudo.

Con este convenio de signos:

$$
F_i>0 \quad \Rightarrow \quad \text{miembro a tracción}
$$

$$
F_i<0 \quad \Rightarrow \quad \text{miembro a compresión}
$$

El signo obtenido no representa una magnitud negativa de fuerza. Indica que el sentido real de la fuerza es contrario al supuesto inicialmente durante la formulación de las ecuaciones de equilibrio.

Las reacciones en los apoyos se interpretan de acuerdo con los sentidos positivos adoptados para los ejes globales de la estructura.

In [7]:
# ============================================================
# INTERPRETACIÓN ESTRUCTURAL DE LAS FUERZAS INTERNAS
# ============================================================

# En este ejemplo, las siete primeras incógnitas
# corresponden a fuerzas internas en los miembros
numero_miembros = 7

print("FUERZAS INTERNAS EN LOS MIEMBROS")
print("=================================")

for i in range(numero_miembros):

    fuerza = T[i, 0]

    if np.isclose(fuerza, 0):
        estado = "FUERZA NULA"
    elif fuerza > 0:
        estado = "TRACCIÓN"
    else:
        estado = "COMPRESIÓN"

    print(
        f"{nombres[i]:>3s} : "
        f"{abs(fuerza):10.4f}  ->  {estado}"
    )

FUERZAS INTERNAS EN LOS MIEMBROS
 F1 :   288.6836  ->  TRACCIÓN
 F2 :   577.3672  ->  COMPRESIÓN
 F3 :   115.4734  ->  TRACCIÓN
 F4 :   346.4203  ->  COMPRESIÓN
 F5 :   115.4734  ->  COMPRESIÓN
 F6 :   404.1570  ->  TRACCIÓN
 F7 :   808.3141  ->  COMPRESIÓN


In [8]:
# ============================================================
# REACCIONES EN LOS APOYOS
# ============================================================

print("REACCIONES EN LOS APOYOS")
print("========================")

for i in range(numero_miembros, n):

    reaccion = T[i, 0]

    print(f"{nombres[i]:>3s} = {reaccion:10.4f}")

REACCIONES EN LOS APOYOS
 Ax =     0.0000
 Ay =   500.0000
 Ey =   700.0000


### 5.1 Verificación del equilibrio global de la estructura

Además de comprobar matricialmente que:

$$
[K_T]\{T\}\approx\{P\}
$$

es conveniente realizar una verificación independiente utilizando las condiciones de equilibrio global de la estructura.

Para las fuerzas verticales:

$$
\sum F_y=0
$$

Las cargas externas aplicadas son:

$$
400+800=1200
$$

mientras que las reacciones verticales obtenidas son:

$$
A_y+E_y=500+700=1200
$$

por tanto:

$$
A_y+E_y-(400+800)=0
$$

y se satisface el equilibrio vertical global.

En dirección horizontal no existen cargas externas aplicadas y se obtuvo:

$$
A_x=0
$$

lo cual también es consistente con el equilibrio global de la estructura.

Esta comprobación constituye una verificación física adicional de los resultados obtenidos mediante la solución matricial.

## 6. Solución directa del sistema de ecuaciones

En la sección anterior el sistema se resolvió mediante:

$$
\{T\}=[K_T]^{-1}\{P\}
$$

Este procedimiento resulta especialmente útil desde el punto de vista pedagógico, porque permite relacionar la solución del problema estructural con conceptos previamente estudiados como el determinante, el rango y la matriz inversa.

Sin embargo, para resolver computacionalmente un sistema lineal no es necesario calcular explícitamente la matriz inversa.

NumPy dispone de la función:

`np.linalg.solve()`

que permite resolver directamente un sistema de la forma:

$$
[A]\{x\}=\{b\}
$$

Por tanto, para el sistema estructural:

$$
[K_T]\{T\}=\{P\}
$$

puede utilizarse:

`np.linalg.solve(KT, P)`

Este procedimiento es, en general, preferible desde el punto de vista computacional, ya que evita el cálculo explícito de la matriz inversa y permite resolver el sistema de manera más directa y eficiente.

A continuación se compararán los resultados obtenidos mediante ambos procedimientos.

In [9]:
# ============================================================
# SOLUCIÓN DIRECTA DEL SISTEMA
# ============================================================

# Solución obtenida anteriormente mediante la matriz inversa
T_inversa = KT_inversa @ P

# Solución directa del sistema
T_solve = np.linalg.solve(KT, P)

print("SOLUCIÓN MEDIANTE LA MATRIZ INVERSA")
print("-----------------------------------")

for i in range(n):
    print(f"{nombres[i]:>3s} = {T_inversa[i, 0]:10.4f}")


print("\nSOLUCIÓN MEDIANTE np.linalg.solve()")
print("----------------------------------")

for i in range(n):
    print(f"{nombres[i]:>3s} = {T_solve[i, 0]:10.4f}")


print("\nCOMPARACIÓN DE LOS RESULTADOS")
print("-----------------------------")

if np.allclose(T_inversa, T_solve):
    print("Los dos procedimientos producen la misma solución.")
else:
    print("Se presentan diferencias entre las soluciones obtenidas.")

SOLUCIÓN MEDIANTE LA MATRIZ INVERSA
-----------------------------------
 F1 =   288.6836
 F2 =  -577.3672
 F3 =   115.4734
 F4 =  -346.4203
 F5 =  -115.4734
 F6 =   404.1570
 F7 =  -808.3141
 Ax =     0.0000
 Ay =   500.0000
 Ey =   700.0000

SOLUCIÓN MEDIANTE np.linalg.solve()
----------------------------------
 F1 =   288.6836
 F2 =  -577.3672
 F3 =   115.4734
 F4 =  -346.4203
 F5 =  -115.4734
 F6 =   404.1570
 F7 =  -808.3141
 Ax =     0.0000
 Ay =   500.0000
 Ey =   700.0000

COMPARACIÓN DE LOS RESULTADOS
-----------------------------
Los dos procedimientos producen la misma solución.


### Interpretación

Los dos procedimientos conducen, dentro de la precisión numérica utilizada, a la misma solución del sistema.

El cálculo mediante la matriz inversa permite comprender con claridad el fundamento algebraico de la solución:

$$
\{T\}=[K_T]^{-1}\{P\}
$$

mientras que `np.linalg.solve()` constituye una alternativa más directa para la solución computacional de sistemas lineales.

Por esta razón, en este ejercicio se utilizó inicialmente la matriz inversa con fines conceptuales y posteriormente se presentó la solución directa como una práctica computacional más adecuada.

## 7. Reflexión final

La solución computacional de una estructura no comienza con la ejecución de un programa. Comienza con la comprensión del comportamiento estructural, la definición de un modelo y la formulación correcta de las ecuaciones que lo representan.

En este ejercicio, las condiciones de equilibrio de los nudos permitieron construir un sistema lineal de la forma:

$$
[K_T]\{T\}=\{P\}
$$

La matriz $[K_T]$ no fue generada automáticamente por Python. Cada una de sus filas surgió de una ecuación de equilibrio y cada una de sus columnas estuvo asociada con una incógnita previamente definida.

La programación permitió posteriormente **organizar, resolver y verificar** el sistema de ecuaciones. Conceptos estudiados previamente, como el determinante, el rango y la matriz inversa, adquirieron así una aplicación directa dentro del análisis estructural.

La solución obtenida tampoco constituye el final del análisis. Los valores calculados deben ser interpretados desde la ingeniería, identificando miembros sometidos a tracción o compresión, analizando las reacciones en los apoyos y comprobando el equilibrio global de la estructura.

El procedimiento desarrollado no está limitado a la armadura utilizada como ejemplo. Una vez formulado correctamente un sistema de $n$ ecuaciones lineales con $n$ incógnitas, el mismo algoritmo puede utilizarse para organizarlo, analizarlo y resolverlo computacionalmente.

Por tanto, la programación no reemplaza los fundamentos de la Estática ni del Análisis Estructural. Por el contrario, permite extenderlos hacia problemas de mayor tamaño y complejidad, en los cuales los procedimientos manuales resultan cada vez menos prácticos.

En síntesis:

$$
\boxed{
\text{Modelo estructural}
\rightarrow
\text{Ecuaciones}
\rightarrow
\text{Matrices}
\rightarrow
\text{Algoritmo}
\rightarrow
\text{Solución}
\rightarrow
\text{Verificación}
\rightarrow
\text{Interpretación}
}
$$

El computador realiza con rapidez las operaciones que le han sido indicadas; corresponde al ingeniero formular correctamente el problema, verificar los resultados y determinar si estos tienen sentido físico.

> **Programar el análisis de una estructura no significa enseñarle estructuras al computador; significa traducir el razonamiento del ingeniero a un lenguaje que el computador pueda ejecutar.**